filter:
    excluded_paths:
        - tests/*

checks:
    php:
        code_rating: true

tools:
    php_sim: true
    php_pdepend: true
    php_analyzer: true
    php_cpd: true
    php_cs_fixer: true
    php_loc: true
    php_code_sniffer:
        config:
            standard: "PSR2"
    php_mess_detector: true
    php_pdepend: true
    php_analyzer: true
    sensiolabs_security_checker: true
    php_changetracking: true
    external_code_coverage: true

