sudo: false

language: php

php:
  - 7.1
  - 7.2
  - 7.3
  - nightly

cache:
  directories:
    - $HOME/.composer/cache

before_install:
  - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{,.disabled} || echo "xdebug not available"

install: travis_retry composer install

script:
  - vendor/bin/phpunit --testsuite=unit
  - vendor/bin/phpunit --testsuite=integration

jobs:
  allow_failures:
    - php: nightly

  include:
    - stage: Quality assurance
      env: CODE_COVERAGE
      before_script:
        - mv ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini{.disabled,}
        - if [[ ! $(php -m | grep -si xdebug) ]]; then echo "xdebug required for coverage"; exit 1; fi
      script: vendor/bin/phpunit --coverage-clover ./clover.xml
      after_script:
        - wget https://scrutinizer-ci.com/ocular.phar
        - php ocular.phar code-coverage:upload --format=php-clover ./clover.xml

    - stage: Quality assurance
      env: DOCHEADER
      script: vendor/bin/docheader check src/ tests/
